# Set theme
remote_theme: daviddarnes/alembic

# File excludes
exclude:
- README.md
- Gemfile
- Gemfile.lock

# Set plugins
plugins:
- jekyll-sitemap
- jekyll-mentions
- jekyll-paginate
- jekyll-seo-tag
- jekyll-redirect-from
- jekyll-default-layout
- jekyll-feed
- jemoji
- jekyll-remote-theme

# Site settings
url: 'https://mydomain.com'
baseurl: ''
title: 'UW EMILAB'
description: ''
permalink: pretty
logo: "/images/logo.jpg"

# Pagination
paginate: 5
paginate_path: news/page:num

# Header nav
navigation_header:
- title: Home
  url: /
- title: Research
  url: /research/
- title: Professional Development
  url: /professional_development/
- title: Publications
  url: /publications/
- title: People
  url: /people/
- title: News
  url: /news/

# Footer nav
navigation_footer:
- title: Back to top
  url: "#top"

# Collections
collections:
  posts:
    title: Posts
    output: true
    description: "My thoughts and ideas"
    feature_text: |
      Group News
    feature_image: "https://picsum.photos/2560/600?image=866"


# Google Analytics
google_analytics: UA-159166256-1

